set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi
bind r source-file "$TERMINAL_IDE_CONFIG_DIR/tmux.conf" \; display-message "tmux config reloaded"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Direct pane navigation.
bind -n M-Left select-pane -L
bind -n M-Down select-pane -D
bind -n M-Up select-pane -U
bind -n M-Right select-pane -R

# Create a pane in the direction of the arrow.
bind -n M-S-Left split-window -hb -c "#{pane_current_path}"
bind -n M-S-Down split-window -v -c "#{pane_current_path}"
bind -n M-S-Up split-window -vb -c "#{pane_current_path}"
bind -n M-S-Right split-window -h -c "#{pane_current_path}"

# Direct window navigation and pane zoom.
bind -n C-S-Left previous-window
bind -n C-S-Right next-window
bind -n M-z resize-pane -Z

# Direct pane resize.
bind -n C-M-Left resize-pane -L 5
bind -n C-M-Down resize-pane -D 3
bind -n C-M-Up resize-pane -U 3
bind -n C-M-Right resize-pane -R 5

bind -r H resize-pane -L 5
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 5
