gui:
  language: pt
  nerdFontsVersion: "3"
  showFileTree: true
  showCommandLog: false
  showBottomLine: true
  showPanelJumps: true
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
git:
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=oneline {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=oneline
os:
  editPreset: nvim-remote

keybinding:
  universal:
    confirmInEditor:
      - <ctrl+enter>
      - <ctrl+s>

disableStartupPopups: true
notARepository: quit
